"""Add user authentication and billing tables

Revision ID: fb9cf81c8e5c
Revises: 42dc056200b9
Create Date: 2025-07-14 20:54:02.873092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb9cf81c8e5c'
down_revision: Union[str, Sequence[str], None] = '42dc056200b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('picture_url', sa.String(length=500), nullable=True),
    sa.Column('credits_remaining', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_credits_purchased', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('usage_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('documents_processed', sa.Integer(), nullable=True),
    sa.Column('anthropic_cost', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('charged_amount', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('markup_multiplier', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['analysis_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('analysis_sessions', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'analysis_sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analysis_sessions', type_='foreignkey')
    op.drop_column('analysis_sessions', 'user_id')
    op.drop_table('usage_records')
    op.drop_table('users')
    # ### end Alembic commands ###
